# Generated by Django 4.2.10 on 2024-02-19 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bookForm", "0002_users_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name="users",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookForm.color",
            ),
        ),
    ]
