# Generated by Django 4.2.10 on 2024-03-12 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="blog",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.post",
            ),
        ),
    ]
