# Generated by Django 4.2.10 on 2024-03-15 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0011_post_like_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="people", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
