# Generated by Django 4.2.10 on 2024-03-15 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_post_like"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
