# Generated by Django 5.0.1 on 2024-02-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookOutlet", "0002_remove_book_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="value",
            field=models.IntegerField(default=0),
        ),
    ]
