# Generated by Django 5.0.1 on 2024-02-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookOutlet', '0003_book_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='value',
        ),
    ]
