# Generated by Django 5.0.1 on 2024-02-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookOutlet", "0006_alter_book_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
