# Generated by Django 5.0.1 on 2024-02-07 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookOutlet', '0011_country_alter_address_options_book_published_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookOutlet.country'),
        ),
    ]
